name: Reminder

on:
  schedule:
    # Every JST 9:00 on workdays
    - cron: "0 0 * * 1,2,3,4,5"
  workflow_dispatch:

env:
  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.5
      - name: Install Dependencies
        run: poetry install --no-interaction
      - name: Run Reminder
        run: poetry run python -m build_standup_bot.reminder
